### ISSUE TITLE
Greeting not changing based on time of day

### ISSUE THREAD

**Issue by yevgenilin5296** [yevgenilin5296/digital-clock#1]
in `app.js`, lines 34-45:

```  if (hours < 12) {
    document.getElementById('greeting').innerHTML = goodMorning;
  }
  if (hours < 17) {
    document.getElementById('greeting').innerHTML = goodAfternoon;
  }
  if (hours < 21) {
    document.getElementById('greeting').innerHTML = goodEvening;
  }
  if (hours < 24) {
    document.getElementById('greeting').innerHTML = goodNight;
  }
```
Is this code correct?

**Comment by jacobvr** [comment]
well not really :)

let's suppose `hours` is `3`
- `if (hours < 12)` true? yes, it will run this block
- `if (hours < 17)` true? huh, yep it is!! so it will run this block next
- `if (hours < 21)` true? of course!! running this block next
- `if (hours < 24)` true? oh yeah!! running this block last

you need an `else` statement for `17`, `21`, and `24`. it will go to `else` if current condition fails:
```
if (hours < 12) { ... }
else if (hours < 17) { ... }
else if (hours < 21) { ... }
...
```

**Comment by yevgenilin5296** [comment]
Oh, how did I forget the `if-else`?! Thanks for the reminder, works great now! :smile:
